clang++ ch.cpp -o ch.exe -O2
clang++ cc.cpp -o cc.exe -O2
clang++ ah.cpp -o ah.exe -O2
clang++ ac.cpp -o ac.exe -O2
clang++ ifv.cpp -o ifv.exe -O2
clang++ ifelse.cpp -o ifelse.exe -O2
clang++ dowhile.cpp -o dowhile.exe -O2
clang++ while.cpp -o while.exe -O2
clang++ dowhile.cpp -o dowhile.exe -O2
clang++ forv.cpp -o forv.exe -O2
clang++ forI.cpp -o forI.exe -O2
clang++ struct.cpp -o struct.exe -O2
clang++ include.cpp -o include.exe -O2
clang++ myAssert.cpp -o myAssert.exe -O2
clang++ func.cpp -o func.exe -O2
clang++ classFile.cpp -o classFile.exe -O2
clang++ convertType.cpp -o convertType.exe -O2
clang++ decltype.cpp -o decltype.exe -O2
clang++ makeUnique.cpp -o makeUnique.exe -O2
clang++ unique_ptr.cpp -o unique_ptr.exe -O2

